# Site settings
title: Introduction to Humanities Programming
description: "An introduction to Humanities Programming course materials for the Humanities Intensive Learning and Teaching (HILT) program."
baseurl: "https://humanitiesprogramming.github.io/intro-to-dh-programming"
url: "https://humanitiesprogramming.github.io/"

# build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed
exclude: ["README.md", "Gruntfile.js", "changelog.md", "Gemfile", "Gemfile.lock", "node_modules", "bower_components", "scss", "config.rb", "package.json", "LICENSE", "bower.json"]

gems:
  - jekyll-sitemap
